version: "3.9"

services:
  photo-booth:
    build: .
    image: photo-booth
    container_name: photo-booth

    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}

    volumes:
      - ./photos:/app/photos

    devices:
      - /dev/video0:/dev/video0

    extra_hosts:
      - "host.docker.internal:host-gateway"
